version: "2"
services:
    web:
        image: nginx:1.12.1
        ports:
            - "80:80"
        volumes:
            - /html/docker/nginx/upstream/nginx.conf:/etc/nginx/nginx.conf
            - /html/docker/nginx/upstream/config:/etc/nginx/config
            - /html/docker/nginx/upstream/vhost:/etc/nginx/vhost